### ISSUE TITLE
RPM containing file with special characters causes repo-creation to fail

### ISSUE THREAD

**Issue by fruetschi** [ctron/rpm-builder#29]
When trying to build a repository RPM with the rpm package of the puppet-agent in it (https://yum.puppetlabs.com/puppet5/el/7/x86_64/puppet-agent-5.3.8-1.el7.x86_64.rpm) the goal yum-repository fails with:
[ERROR] Failed to execute goal de.dentrassi.maven:rpm:0.9.2:yum-repository (create-yum-repo-puppet) on project xvp-repo-puppet: Execution create-yum-repo-puppet of goal de.dentrassi.maven:rpm:0.9.2:yum-repository failed: java.nio.charset.MalformedInputException: Input length = 1 -> [Help 1] 

The file that causes the exception is located in the puppet-agent rpm at ".\opt\puppetlabs\puppet\lib\ruby\gems\2.4.0\gems\hocon-1.2.5\spec\fixtures\test_utils\resources\ᚠᛇᚻ.conf".

**Comment by ctron** [comment]
This looks indeed like a bug. Could you provide the full stack trace. IIRC running with `mvn -X -e` should give your more output.

**Comment by fruetschi** [comment]
[ERROR] Failed to execute goal de.dentrassi.maven:rpm:0.9.2:yum-repository (create-yum-repo-puppet) on project xvp-repo-puppet: Execution create-yum-repo-puppet of goal de.dentrassi.maven:rpm:0.9.2:yum-repository failed: java.nio.charset.MalformedInputException: Input length = 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.dentrassi.maven:rpm:0.9.2:yum-repository (create-yum-repo-puppet) on project xvp-repo-puppet: Execution create-yum-repo-puppet of goal de.dentrassi.maven:rpm:0.9.2:yum-repository failed: java.nio.charset.MalformedInputException: Input length = 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution create-yum-repo-puppet of goal de.dentrassi.maven:rpm:0.9.2:yum-repository failed: java.nio.charset.MalformedInputException: Input length = 1
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
	at de.dentrassi.rpm.builder.YumMojo.addPackageList(YumMojo.java:227)
	at de.dentrassi.rpm.builder.YumMojo.execute(YumMojo.java:205)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
	at org.apache.commons.compress.archivers.zip.NioZipEncoding.decode(NioZipEncoding.java:118)
	at org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream.readCString(CpioArchiveInputStream.java:447)
	at org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream.readNewEntry(CpioArchiveInputStream.java:380)
	at org.apache.commons.compress.archivers.cpio.CpioArchiveInputStream.getNextCPIOEntry(CpioArchiveInputStream.java:246)
	at org.eclipse.packagedrone.utils.rpm.info.RpmInformations.makeInformation(RpmInformations.java:103)
	at de.dentrassi.rpm.builder.YumMojo.addSinglePackage(YumMojo.java:241)
	at de.dentrassi.rpm.builder.YumMojo.lambda$addPackageList$4(YumMojo.java:220)
	at org.eclipse.packagedrone.utils.rpm.yum.RepositoryCreator.lambda$null$5(RepositoryCreator.java:613)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$open$1(OutputSpooler.java:204)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:213)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$openNext$2(OutputSpooler.java:249)
	at org.eclipse.packagedrone.utils.io.FileSystemSpoolOutTarget.spoolOut(FileSystemSpoolOutTarget.java:38)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:218)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$openNext$2(OutputSpooler.java:249)
	at org.eclipse.packagedrone.utils.io.FileSystemSpoolOutTarget.spoolOut(FileSystemSpoolOutTarget.java:38)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:218)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.open(OutputSpooler.java:201)
	at org.eclipse.packagedrone.utils.rpm.yum.RepositoryCreator.lambda$null$6(RepositoryCreator.java:611)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$open$1(OutputSpooler.java:204)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:213)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$openNext$2(OutputSpooler.java:249)
	at org.eclipse.packagedrone.utils.io.FileSystemSpoolOutTarget.spoolOut(FileSystemSpoolOutTarget.java:38)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:218)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$openNext$2(OutputSpooler.java:249)
	at org.eclipse.packagedrone.utils.io.FileSystemSpoolOutTarget.spoolOut(FileSystemSpoolOutTarget.java:38)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:218)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.open(OutputSpooler.java:201)
	at org.eclipse.packagedrone.utils.rpm.yum.RepositoryCreator.lambda$process$7(RepositoryCreator.java:610)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$open$1(OutputSpooler.java:204)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:213)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$openNext$2(OutputSpooler.java:249)
	at org.eclipse.packagedrone.utils.io.FileSystemSpoolOutTarget.spoolOut(FileSystemSpoolOutTarget.java:38)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:218)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.lambda$openNext$2(OutputSpooler.java:249)
	at org.eclipse.packagedrone.utils.io.FileSystemSpoolOutTarget.spoolOut(FileSystemSpoolOutTarget.java:38)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.openNext(OutputSpooler.java:218)
	at org.eclipse.packagedrone.utils.io.OutputSpooler.open(OutputSpooler.java:201)
	at org.eclipse.packagedrone.utils.rpm.yum.RepositoryCreator.process(RepositoryCreator.java:609)
	at de.dentrassi.rpm.builder.YumMojo.addPackageList(YumMojo.java:217)
	... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by ctron** [comment]
Ok, so that is indeed a bug in the Package Drone base library. Which should open the CPIO stream with UTF-8 instead of US-ASCII.

**Comment by ctron** [comment]
This should be solved with version 1.0.1 of the plugin which I just released. Please re-open otherwise.

**Comment by ctron** [comment]
And it looked so simple :grin:

**Comment by ctron** [comment]
Congratulations … you just found an issue in Apache Commons Compress :wink: … I won't be able to fix this as quickly as when it was in the RPM code.

But I will file an issue in Commons Compress and try to provide a fix for it.

In a nutshell I does handle the length of names wrong as it assumes one byte per character, which isn't true anymore for UTF-8.

**Comment by ctron** [comment]
https://issues.apache.org/jira/browse/COMPRESS-459

**Comment by ctron** [comment]
I will try to follow up on this one, however it might take a bit longer.

**Comment by ctron** [comment]
Apache Commons Compress 1.18 was released a few days back. And it does include my fix for the issue. So I will create a new release of the Maven Plugin, which should fix this.

**Comment by ctron** [comment]
I created an integration test for this issue, and it looks like to fix works. So I will create a new version.

**Comment by ctron** [comment]
1.0.3 is releases. I am closing this one. It would be great if you could test it as well and give some feedback.
